# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://edenrabbie.com
title: Eden Rabbie
email: eden@edenrabbie.com
author: Eden Rabbie
description: > # "Write an awesome description for your new site here. 
  Business strategy and product manager in UAE.
copyright: ''
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Email
    icon: far fa-envelope
    url: mailto:eden@edenrabbie.com
  - title: LinkedIn
    icon: fab fa-linkedin
    url: https://linkedin.com/in/edenrabbie
  - title: twitter
    icon: fab fa-twitter
    url: https://twitter.com/edenrabbie
  - title: Medium
    icon: fab fa-medium
    url: https://medium.com/@edenrabbie

